title: DZW0703
e-mail: dezhenwang0703@163.com
description: "个人主页 — DZW0703"
baseurl: "" # 部署在根目录时留空
url: "https://DZW0703.github.io"
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
paginate: 5
collections: {}

plugins: []
